# Generated by Django 4.2 on 2024-08-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='user',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
